name: Submission

on:
  pull_request_target:
    branches: [master]
    types: [opened, reopened, synchronize, edited]

permissions:
  contents: read
  pull-requests: read

jobs:
  submission:
    name: Automated submission checks
    uses: web-programming-contest/web-programming-ci-utils/.github/workflows/submission.yml@c2a6a469bfe9917bbb9c724d58844da2c46d543a
    with:
      utils_repository: web-programming-contest/web-programming-ci-utils
      utils_ref: "c2a6a469bfe9917bbb9c724d58844da2c46d543a"
