name: Submission

on:
  pull_request_target:
    branches: [master]
    types: [opened, reopened, synchronize, edited]

permissions:
  contents: read
  pull-requests: read

jobs:
  submission:
    name: Automated submission checks
    uses: web-programming-contest/web-programming-ci-utils/.github/workflows/submission.yml@fc0b165e627ada9c60f7b1eaa0b646538c788351
    with:
      utils_repository: web-programming-contest/web-programming-ci-utils
      utils_ref: "fc0b165e627ada9c60f7b1eaa0b646538c788351"
